server:
    port: 8182

# seata 日志级别
logging:
    level:
        io:
            seata: info

# 数据源 seata 事务分组
spring:
    application:
        name: storage-server
    cloud:
        alibaba:
            seata:
                tx-service-group: my_test_tx_group
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://121.43.183.45:3306/seata
        username: root
        password: shmliy

# eureka 注册中心
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

# mybatis 配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.seata.sample.entity